### PR TITLE
#161376806 Add approver data to an approved request

### PR DESCRIPTION
**Pull request by Nedson202**
#### What does this PR do?
* Modifies getUserRequestDetails method to include approver information for approved request.

#### Description of Task to be completed?
- append approver data to a request when a request is approved
- update previous test to accommodate changes introduced

#### How should this be manually tested?
- Clone the repository and enter the project's folder
- Checkout to ft-update-dummy-approver-data-161376806
- Assign yourself the manager role by changing your roleId to 53019 in the UserRoles table
- Install dependencies using yarn
- Rollback and run database migrations with yarn db:rollmigrate
- Start the server with make start
- Setup the frontend using this [guide](https://github.com/andela/travel_tool_front/pull/233)

#### Any background context you want to provide?
This PR is necessary to run the [frontend](https://github.com/andela/travel_tool_front/pull/233)

#### What are the relevant pivotal tracker stories?
[#161376806](https://www.pivotaltracker.com/story/show/161376806)

#### Screenshots (if appropriate)
screen shot 2018-10-24 at 1 07 14 pm

#### Questions:
N/A

### CODE REVIEW

**Comment by ssewilliam** [comment]
@Nedson202, I think you have a typo in how this can be manually tested?

**Comment by Nedson202** [comment]
Thanks for pointing this out. Based on the latest changes regarding rooms, it can easily get complicated trying to test the backend as a different unit and as such, I've decided to update the description to work in hand with the branch on the frontend.

**Comment by asamisellah** [comment]
@Nedson202 I have reviewed this feature and it's working as expected. LGTM.

**Comment by Nedson202** [comment]
Tried checking what could be the cause on codeclimate but nothing was returned. I will still look into this and see what can be done.

**Comment by Nedson202** [comment]
Hi @davenjeru, were you able to later edit the request. The issue was the typo in the location provided in the guesthouse seed and that has been corrected.

**Comment by davenjeru** [comment]
Yes I was...

**Comment by babadee001** [comment]
Why do we have a drop in coverage? @Nedson202

**Comment by Nedson202** [comment]
This is as a result of some validators not totally targetted in test files.

**Pull request merged**
