### PR TITLE
#161050888 View deleted travel checklist items

### PR DESCRIPTION
**Pull request by ssewilliam**
#### What does this PR do?
- Allows an Admin to view deleted travel checklist items

#### Description of Task to be completed?
- Admin should see a list of deleted travel checklist items

#### How should this be manually tested?
- Clone the repository and enter the project's folder
- Checkout to **ft-view-deleted-checklist-items-161050888**
- Assign yourself the travel admin role by changing your roleId to 29187 in the users table
- Start the application using 'make start'
- Open postman and provide your token in the authorization header.
- Create a new travel checklist item using the create endpoint, **/api/v1/checklists**

```
{	
   "name": "Passport", 
   "requiresFiles": "false", 
   "resources": [{
	"link": "No link",
	"label": "No Link"
    }]
}
```

- Delete that item using the delete endpoint, **/api/v1/checklists/ChecklistItemId** 
```
{
    "deleteReason": "This was a double record",
}
```

- Fetch the item deleted using the fetch endpoint, **api/v1/checklists/deleted?destinationName=YourDestinationCity**
```{
    "success": true,
    "message": "deleted travel checklist items retrieved successfully",
    "deletedTravelChecklists": [
        {
            "id": "joZWu_ELS",
            "name": "Passport",
            "requiresFiles": false,
            "deleteReason": "This was a double record",
            "destinationName": "Lagos, Nigeria",
            "createdAt": "2018-10-24T07:48:40.317Z",
            "updatedAt": "2018-10-24T07:56:58.689Z",
            "deletedAt": "2018-10-24T07:56:58.703Z"
        }
    ]
}
```

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#161050888](https://www.pivotaltracker.com/story/show/161050888)

#### Screenshots (if appropriate)
- Create the item
screen shot 2018-10-24 at 10 55 52

- Delete the item
screen shot 2018-10-24 at 11 11 12

- Fetch the deleted Item
screen shot 2018-10-24 at 10 50 18

#### Questions:
- How would I simulate a server failure so as to return 500 error status code?

### CODE REVIEW

**Comment by Nedson202** [comment]
Please update your commit to follow this [commit_message_convention](https://github.com/andela/engineering-playbook/blob/master/5.%20Developing/Conventions/readme.md#message-footer) on the engineering playbook.

**Comment by ssewilliam** [comment]
@Nedson202, I have worked on your changes. This PR now follows the commit_message_convention as per the engineering playbook

**Comment by Nedson202** [comment]
Can you point us to the location @davenjeru

**Comment by ssewilliam** [comment]
@davenjeru, I have worked on your changes. The guide now shows that the user no longer needs to pass in the **itemToEdit** and **ChecklistItemId**

**Comment by davenjeru** [comment]
> Can you point us to the location @davenjeru

It was on the PR description.

**Pull request merged**
