### PR TITLE
#161618118 Fix checklist percentage error

### PR DESCRIPTION
**Pull request by clintfidel**
#### What does this PR do?
This PR ensures that travel checklist percentage error is based on a destination

#### Description of Task to be completed?
- get the right checklist for a destination

#### How should this be manually tested?
* checkout to this branch `bg-fix-checklist-percentage-error-161618118`
*install dependencies `make install`
*start server `make start`
*Navigate to travela in your browser and log in
*Login on your browser and copy the jwt_token from the application tab in Developers tab
*Open Postman
*Add a request and select `POST` method
*Add jwt token in headers with key `Authorization`
*Add `Content-Type` with value `application/json`
*Make a get request with the endpoint  using 
`http://localhost:5000/api/v1/requests`

#### What are the relevant pivotal tracker stories?
[#161618118](https://www.pivotaltracker.com/story/show/161618118)

### CODE REVIEW

**Comment by Nedson202** [comment]
LGTM

**Comment by babadee001** [comment]
Kindly resolve conflicts @clintfidel

**Comment by samuelkubai** [comment]
@matthewacha maybe this pr contains what you need.

**Comment by matthewacha** [comment]
@samuelkubai it does not take into account the air ticket submissions

**Pull request merged**
