### PR TITLE
#160195740 Create Endpoint To Get User Request Details

### PR DESCRIPTION
**Pull request by clintfidel**
#### What does this PR do?
creates an endpoint to get request details of a user

#### Description of Task to be completed?

- write test for endpoint to get a user request details
- create method/function to enable to get a user request details
- create endpoint - `http://localhost:5000/api/v1/requests/:requestId`

#### How should this be manually tested?
- Clone the repo -git clone https://github.com/andela/travel_tool_back.git
- Enter into the project directory using - `cd travel_tool_back`
- Start the app using `make start`
- Login on your browser and grab your token from the application tab in Developers tab(cookies)
- Open Postman
- Add your token in headers- e.g `Authorization: 'hhdbvvvfgvcgcgvfcscfxcx`
- Send a Get request to `http://localhost:5000/api/v1/requests/:requestId`
 
#### Any background context you want to provide?
None

#### What are the relevant pivotal tracker stories?
[160195740](https://www.pivotaltracker.com/story/show/160195740)

#### Screenshots (if appropriate)
screen shot 2018-09-04 at 12 33 00 pm

### CODE REVIEW

**Comment by clintfidel** [comment]
@albert85 I have implemented your feedback, please confirm.

**Comment by clintfidel** [comment]
@d3mola I have implemented the feedback given, kindly review

**Comment by clintfidel** [comment]
@albert85 it has been fixed

**Comment by babadee001** [comment]
LGTM @samuelkubai

**Comment by seunzone** [comment]
LGTM

**Pull request merged**
